services:
    db:
        image: mongo:7
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: soc
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: soc
        env_file:
            - .env.development
            - .env.local

    mongo-express:
        image: mongo-express
        depends_on:
            - db
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_URL: mongodb://soc:password@db:27017/
        env_file:
            - .env.local
